# This is one of your sites.
version: '2.4'

services:
  4soulsband_wordpress:
    container_name: 4soulsband_wordpress
    image: wordpress:php8.0

    cpu_quota: 10000  # 1000 = 1%
    mem_reservation: 256M
    restart: always

    depends_on:
      - 4soulsband_mysql_db
    env_file: deploy_configs/env_vars/4soulsband_wordpress.env
    volumes:
      - ./4soulsband_wordpress:/var/www/html
    labels:
      - traefik.http.routers.4soulsband_wordpress.rule=Host(`4soulsband.duckdns.org`)
      - traefik.http.routers.4soulsband_wordpress.tls.certresolver=${CASERVER}
      - traefik.http.services.4soulsband_wordpress.loadbalancer.server.port=80
      - traefik.docker.network=traefik_proxy_net

      - traefik.enable=true
      - traefik.http.routers.4soulsband_wordpress.entrypoints=http,https
      - traefik.http.routers.4soulsband_wordpress.tls=true
    networks:
      traefik_proxy_net:
      4soulsband_net:

  4soulsband_mysql_db:
    container_name: 4soulsband_mysql_db
    image: mysql/mysql-server:8.0

    cpu_quota: 10000  # 1000 = 1%
    mem_reservation: 512M
    restart: always

    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./deploy_configs/env_vars/4soulsband_wordpress.env
    volumes:
      - ./4soulsband_mysql_db:/var/lib/mysql
    networks:
      4soulsband_net:
      traefik_proxy_net:  # To get access to a db by domain name.

  redis:
    image: redis:6.0.15-alpine
    container_name: redis

    cpu_quota: 20000  # 1000 = 1%
    mem_reservation: 512M
    restart: always

    command: --port 6380
    entrypoint: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    security_opt:
      - no-new-privileges:true
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      4soulsband_net:

  4soulsband_backup:
    container_name: 4soulsband_backup
    image: blacklabelops/volumerize:1.7.1
    volumes:
      - ./4soulsband_mysql_db:/source/db:ro
      - ./4soulsband_wordpress:/source/wp:ro
      - ./4soulsband_backup:/backup
    restart: always
#    command: restore --dry-run  # For testing
    environment:
      VOLUMERIZE_SOURCE: /source
      VOLUMERIZE_TARGET: file:///backup
      TZ: Asia/Novosibirsk
      VOLUMERIZE_JOBBER_TIME: 0 0 6 1 * *
      VOLUMERIZE_CONTAINERS: 4soulsband_mysql_db 4soulsband_wordpress
    networks:
      4soulsband_net:

networks:
  4soulsband_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.193.0/24

  traefik_proxy_net:
    external: true

  redis_net:
    external: true

volumes: # Persistent data
  db:
  wp:
  backup:
