version: '2.4'

services:
#  zabbix-agent:
#    image: zabbix/zabbix-agent:ubuntu-5.0.16
#
#    cpu_quota: 5000  # 1000 = 1%
#    mem_reservation: 8M
#
#    ports:
#      - "10050:10050"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
#      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
#      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
#      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
#    env_file:
#      - ./deploy_configs/env_vars/.env_agent
#    privileged: true
#    pid: "host"
#    networks:
#      wordpress_net:
#    stop_grace_period: 5s
#    restart: always

#  traefik:
#    image: traefik:v2.5.3
#
#    cpu_quota: 10000  # 1000 = 1%
#    mem_reservation: 64M
#
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - traefik-ssl-certs:/ssl-certs
#      - ./deploy_configs/traefik/:/etc/traefik/
#      - /etc/localtime:/etc/localtime:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.dashboard.rule=Host(`traefik.zabbix-web24.duckdns.org`)"
#      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
#
#      - "traefik.http.routers.dashboard.tls=true"
#      - "traefik.http.routers.dashboard.entrypoints=http,https"
#      - "traefik.http.routers.dashboard.middlewares=secheaders@file"
#      - "traefik.http.routers.dashboard.tls.certresolver=staging"
#
#      # Basic Authentication for Traefik Dashboard
#      # Generate password: sudo apt update && sudo apt install apache2-utils && htpasswd -nb USER PASSWORD
#      # You need to escape all $ sings ($ --> $$)
#      - "traefik.http.routers.dashboard.service=api@internal"
#      - "traefik.http.routers.dashboard.middlewares=traefik-auth"
#      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$dQS.9m8b$$99bHXnFsbxXaa5StcfPRk/"
#    healthcheck:
#      test: [ "CMD", "wget", "http://localhost:8082/ping","--spider" ]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 5s
#    security_opt:
#      - no-new-privileges:true
#    networks:
#      wordpress_net:
#    restart: always

#  wordpress:
#    image: wordpress:php7.4-apache
#    depends_on:
#      - mysql
#    environment:
#      - WORDPRESS_DB_HOST=mysql
#      - WORDPRESS_DB_USER=root
#      - WORDPRESS_DB_NAME=wordpress
#      - WORDPRESS_DB_PASSWORD=password
#    expose:
#      - 80
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.wordpress.rule=Host(`wordpressdemo.net`)
#    networks:
#      wordpress_net:
#    restart: always

  mysql:
    platform: linux/amd64
    image: mysql:8.0.27
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=password
    networks:
      wordpress_net:

networks:
  wordpress_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.249.0/24

volumes: # Persistent data
  traefik-ssl-certs: